### PR TITLE
Update docs to reflect licensing changes

### PR DESCRIPTION
**Pull request by mechanomi**
## Summary of the changes / Why this is an improvement

See https://github.com/crate/tech-writing-domain/issues/380 for more info.

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by amotl** [comment]
I am preparing the release of 0.17.1, see #703. Shall we just go ahead and bring in this update before, too?

**Comment by mechanomi** [comment]
@amotl left a comment here: https://github.com/crate/crate-admin/pull/703

**Comment by amotl** [comment]
Hi Naomi,

I have to admit I didn't have a detailed look at this patch you've handed in here, sorry. However, I believe #707 already addressed all of these updates you suggested here.

Let me know if you think all will be fine in order to proceed with #703.

With kind regards,
Andreas.

**Comment by amotl** [comment]
> Let me know if you think all will be fine in order to proceed with #703.

Do you believe we can close this PR?

**Comment by mechanomi** [comment]
sounds good to me @amotl! thx

**Pull request closed without merging**
