### PR TITLE
Sandbox: Update to Node.js 22.10 and NPM 10.9

### PR DESCRIPTION
**Pull request by amotl**
## About
Just maintenance: Update sandbox environment from previous Node.js 20 LTS to use the most recent Node.js 22 LTS.

### CODE REVIEW

**Comment by kneth** [comment]
It looks like we have to wait for https://github.com/sass/node-sass/pull/3418 to be merged (if it ever will be fixed).

**Comment by amotl** [comment]
After removing `node-sass` from the list of dependencies, the build on CI completes successfully. Because this feels too easy, it would need manual verification that nothing goes south before merging.

**Review by kneth — APPROVED** [review]

**Comment by amotl** [comment]
This patch is incomplete. That other one makes the update successful.

- GH-864

**Comment by amotl** [comment]
Superseded by GH-864, closing.

**Pull request closed without merging**
