### PR TITLE
Change browser scrollbar appearance to fit with rest of UI

### PR DESCRIPTION
**Pull request by proddata**
## Summary of the changes / Why this is an improvement
image

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by msbt** [comment]
@proddata I'll try to fire up a local CrateDB instance to check the styles (and maybe include a solution for non-webkit-browsers as well), not sure if I manage today, will let you know asap!

**Review by amotl — APPROVED** [review]
Thank you!

**Comment by proddata** [comment]
> @proddata I'll try to fire up a local CrateDB instance to check the styles (and maybe include a solution for non-webkit-browsers as well), not sure if I manage today, will let you know asap!

I think there is no css-solution for Firefox :( 

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#browser_compatibility

**Comment by msbt** [comment]
@proddata true, but there's https://www.digitalocean.com/community/tutorials/css-scrollbars / https://codepen.io/team/css-tricks/pen/QWWXQzE - that would be a start ;)

**Comment by proddata** [comment]
alright 😛 

To be fair, the default scrollbars in Firefox 🦊 already looked nice.

**Comment by msbt** [comment]
Hah nice, thanks! Still didn't get around to fire up CrateDB to check it out 😬

**Comment by msbt** [comment]
looking good @proddata (only tested on Ubuntu), but we might keep an eye on contrast, this is not [WCAG compliant](https://webaim.org/resources/contrastchecker/?fcolor=545454&bcolor=2E2E2E), but I don't know if that's something we have to consider in the dark theme

**Comment by amotl** [comment]
> if that's something we have to consider in the dark theme

Currently, we have the dark theme only.

**Review by msbt — APPROVED** [review]

**Pull request merged**
